### ISSUE TITLE
Invalid Syntax in mode.py

### ISSUE THREAD

**Issue by byrleyar** [digidotcom/xbee-python#218]
I am trying to get xbee-python up and running in Arch using pycharm.  I've got a project setup using python 3.9.  When I add `from digi.xbee.devices import XBeeDevice` to main.py, I get the following error:

Traceback (most recent call last):
  File "/home/andrew/PycharmProjects/xbee/main.py", line 15, in <module>
    from digi.xbee.devices import XBeeDevice
  File "/home/andrew/PycharmProjects/xbee/venv/lib/python3.9/site-packages/digi/xbee/devices.py", line 22, in <module>
    from digi.xbee import serial
  File "/home/andrew/PycharmProjects/xbee/venv/lib/python3.9/site-packages/digi/xbee/serial.py", line 21, in <module>
    from digi.xbee.models.mode import OperatingMode
  File "/home/andrew/PycharmProjects/xbee/venv/lib/python3.9/site-packages/digi/xbee/models/mode.py", line 230
    return sum(op.code for op in options if lambda option: option != cls.EXPLICIT)
                                            ^
SyntaxError: invalid syntax

_Note: the carrot falls directly under the "l" in lambda_

**Comment by tatianaleon** [comment]
Hi @byrleyar,

Thanks for reporting. This issue is already fixed in master (see commit https://github.com/digidotcom/xbee-python/commit/ddbff360c0553b30fac1e7d97c1dfbd1b99db09b and issue https://github.com/digidotcom/xbee-python/issues/204) and will be included in the next release.

In the meantime, you can download the source code from the master branch and install the library from there (see instructions at https://github.com/digidotcom/python-xbee/blob/master/README.rst#install-from-source).

Sorry for the inconvenience.

Best regards.
