### ISSUE TITLE
Error UART(1) in use

### ISSUE THREAD

**Issue by MarianoFr** [digidotcom/xbee-python#239]
Hi
Environment:
*Windows 10
*PyCharm with Digi extension
*Using Xbee 3 cellular LTE-m/NB-IoT
With the following code

```
from machine import UART
import time

def main():
    while True:
        uart = UART(1, 9600)
        uart.init(9600, bits=8, parity=None, stop=1, timeout=500)
        if uart.any() > 0:
            message = uart.read()
        time.sleep(2)

if __name__ == "__main__":
    main() 
```

I keep getting the error: 
```
Traceback (most recent call last):
  File "/flash/main.py", line 14, in <module>
  File "/flash/main.py", line 7, in main
ValueError: UART(1) in use
```

From what I read, UART(1) is the secondary uart in the Xbee. If I run this code through XCTU micropython terminal it works ok.
Any ideas?

**Comment by MarianoFr** [comment]
I realized my mistake XD by
