### ISSUE TITLE
Can't set channel via library.

### ISSUE THREAD

**Issue by voney** [digidotcom/xbee-python#292]
Hi, I'm not entirely sure if I'm doing something wrong, but I'm having trouble setting the channel of a modem via the library. Whenever I try to I get a "Status error".

Output from python terminal minimal example:
``` python
>>> from digi.xbee.devices import XBeeDevice
>>> import logging
>>> logging.basicConfig()
>>> logging.getLogger().setLevel("DEBUG")
>>> b = XBeeDevice("/dev/ttyUSB0",115200)
>>> b.open()
INFO:digi.xbee.devices:XBeeSerialPort '/dev/ttyUSB0' port opened
DEBUG:digi.xbee.sender:XBeeSerialPort '/dev/ttyUSB0' - SENT - OperatingMode.API_MODE: 7E 00 04 09 01 41 50 64
DEBUG:digi.xbee.reader:XBeeSerialPort '/dev/ttyUSB0' - RECEIVED - OperatingMode.API_MODE: 7E 00 06 88 01 41 50 00 01 E4
DEBUG:digi.xbee.sender:XBeeSerialPort '/dev/ttyUSB0' - SENT - OperatingMode.API_MODE: 7E 00 04 09 02 48 56 56
DEBUG:digi.xbee.reader:XBeeSerialPort '/dev/ttyUSB0' - RECEIVED - OperatingMode.API_MODE: 7E 00 07 88 02 48 56 00 41 56 40
DEBUG:digi.xbee.sender:XBeeSerialPort '/dev/ttyUSB0' - SENT - OperatingMode.API_MODE: 7E 00 04 09 03 56 52 4B
DEBUG:digi.xbee.reader:XBeeSerialPort '/dev/ttyUSB0' - RECEIVED - OperatingMode.API_MODE: 7E 00 07 88 03 56 52 00 10 0D AF
DEBUG:digi.xbee.sender:XBeeSerialPort '/dev/ttyUSB0' - SENT - OperatingMode.API_MODE: 7E 00 04 09 04 53 48 57
DEBUG:digi.xbee.reader:XBeeSerialPort '/dev/ttyUSB0' - RECEIVED - OperatingMode.API_MODE: 7E 00 09 88 04 53 48 00 00 13 A2 00 23
DEBUG:digi.xbee.sender:XBeeSerialPort '/dev/ttyUSB0' - SENT - OperatingMode.API_MODE: 7E 00 04 09 05 53 4C 52
DEBUG:digi.xbee.reader:XBeeSerialPort '/dev/ttyUSB0' - RECEIVED - OperatingMode.API_MODE: 7E 00 09 88 05 53 4C 00 42 3D 8E D1 F5
DEBUG:digi.xbee.sender:XBeeSerialPort '/dev/ttyUSB0' - SENT - OperatingMode.API_MODE: 7E 00 04 09 06 4E 49 59
DEBUG:digi.xbee.reader:XBeeSerialPort '/dev/ttyUSB0' - RECEIVED - OperatingMode.API_MODE: 7E 00 14 88 06 4E 49 00 47 41 54 45 57 41 59 5F 50 52 49 4D 41 52 59 45
DEBUG:digi.xbee.sender:XBeeSerialPort '/dev/ttyUSB0' - SENT - OperatingMode.API_MODE: 7E 00 04 09 07 4D 59 49
DEBUG:digi.xbee.reader:XBeeSerialPort '/dev/ttyUSB0' - RECEIVED - OperatingMode.API_MODE: 7E 00 07 88 07 4D 59 00 FF FE CD
DEBUG:digi.xbee.sender:XBeeSerialPort '/dev/ttyUSB0' - SENT - OperatingMode.API_MODE: 7E 00 04 09 08 43 45 66
DEBUG:digi.xbee.reader:XBeeSerialPort '/dev/ttyUSB0' - RECEIVED - OperatingMode.API_MODE: 7E 00 06 88 08 43 45 00 00 E7
DEBUG:digi.xbee.sender:XBeeSerialPort '/dev/ttyUSB0' - SENT - OperatingMode.API_MODE: 7E 00 04 09 09 53 4D 4D
DEBUG:digi.xbee.reader:XBeeSerialPort '/dev/ttyUSB0' - RECEIVED - OperatingMode.API_MODE: 7E 00 06 88 09 53 4D 00 00 CE
>>> b.set_parameter("CH", b"\x0f")
DEBUG:digi.xbee.sender:XBeeSerialPort '/dev/ttyUSB0' - SENT - OperatingMode.API_MODE: 7E 00 05 08 0A 43 48 0F 53
DEBUG:digi.xbee.reader:XBeeSerialPort '/dev/ttyUSB0' - RECEIVED - OperatingMode.API_MODE: 7E 00 05 88 0A 43 48 01 E1
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/.cache/pypoetry/virtualenvs/gateway/lib/python3.9/site-packages/digi/xbee/devices.py", line 2052, in dec_function
    return func(self, *args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/gateway/lib/python3.9/site-packages/digi/xbee/devices.py", line 2618, in set_parameter
    super().set_parameter(parameter, value, apply=apply)
  File "/root/.cache/pypoetry/virtualenvs/gateway/lib/python3.9/site-packages/digi/xbee/devices.py", line 356, in set_parameter
    self.__send_parameter(parameter, parameter_value=value, apply=apply)
  File "/root/.cache/pypoetry/virtualenvs/gateway/lib/python3.9/site-packages/digi/xbee/devices.py", line 429, in __send_parameter
    self._check_at_cmd_response_is_valid(response)
  File "/root/.cache/pypoetry/virtualenvs/gateway/lib/python3.9/site-packages/digi/xbee/devices.py", line 449, in _check_at_cmd_response_is_valid
    raise ATCommandException(message=response.status.description,
digi.xbee.exception.ATCommandException: Status Error
```

**Comment by rubenmoral** [comment]
Hey @voney, it seems your device is running a Zigbee 3.0 firmware, which does not support explicit channel selection. The `CH` parameter is read-only and returns the channel number of the attached network. In Zigbee, you can only change the channels used when an active scan is performed through the `SC` parameter. You have more details here:
* https://www.digi.com/resources/documentation/digidocs/90001539/#reference/r_cmd_sc.htm
* https://www.digi.com/resources/documentation/digidocs/90001539/#concepts/c_zb_channel_selection.htm
