### ISSUE TITLE
AttributeError exception with enum.py module python3.7

### ISSUE THREAD

**Issue by kamilmuza** [digidotcom/xbee-python#68]
`Traceback (most recent call last):
  File "/Users/kmuza/Aquicore/repos/asmund/pc_dfu/update.py", line 181, in main
    print(remote_pinout.get_micro_selected())
  File "/Users/kmuza/Aquicore/repos/asmund/pc_dfu/gpio_control.py", line 29, in get_micro_selected
    return self.remote_xbee_sx.get_io_configuration(STM_XBEE_MUX)
  File "/Users/kmuza/venvs/asmund3.7/lib/python3.7/site-packages/digi/xbee/devices.py", line 645, in get_io_configuration
    mode = IOMode.get(self.get_parameter(io_line.at_command)[0])
  File "/Users/kmuza/.pyenv/versions/3.7.1/Python.framework/Versions/3.7/lib/python3.7/enum.py", line 348, in __getattr__
    raise AttributeError(name) from None
AttributeError: get`

Getting an exception when trying to `get_io_configuration` from a remote xbee. 
Using `get_dio_value` seems to be working fine though

**Comment by tatianaleon** [comment]
Hi @Eric-Levine,

Thanks for reporting this issue. It is already fixed (see commit https://github.com/digidotcom/xbee-python/commit/8e40b6675ad6a78b69257092326f29361286a8a3) and included in 1.3.0 release.

Sorry for the inconvenience.

Best regards.
